export const KEYBOARD_NAVIGATION_NODE = Object.freeze({
  NORMAL: "normal",
  EDITING: "editing",
  HINT: "hint",
  SCROLL_SELECTING: "scroll-selecting",
  SCROLL_ACTIVE: "scroll-active",
  SHORTCUT_HELP: "shortcut-help",
});

export const KEYBOARD_NAVIGATION_EVENT = Object.freeze({
  ENTRY_REJECTED: "entry-rejected",
  EDITING_STARTED: "editing-started",
  EDITING_CONTINUED: "editing-continued",
  EDITING_ENDED: "editing-ended",
  HINT_STARTED: "hint-started",
  HINT_INPUT_CHANGED: "hint-input-changed",
  HINT_CANCELLED: "hint-cancelled",
  HINT_CLOSED_FOR_ACTIVATION: "hint-closed-for-activation",
  SCROLL_SELECTION_STARTED: "scroll-selection-started",
  SCROLL_SELECTION_INPUT_CHANGED: "scroll-selection-input-changed",
  SCROLL_SELECTION_CANCELLED: "scroll-selection-cancelled",
  SCROLL_STARTED: "scroll-started",
  SCROLL_SURFACE_SELECTED: "scroll-surface-selected",
  SCROLL_COMMAND: "scroll-command",
  SCROLL_CANCELLED: "scroll-cancelled",
  SHORTCUT_HELP_STARTED: "shortcut-help-started",
  SHORTCUT_HELP_CLOSED: "shortcut-help-closed",
});

export const KEYBOARD_NAVIGATION_GRAPH = Object.freeze({
  [KEYBOARD_NAVIGATION_NODE.NORMAL]: Object.freeze({
    [KEYBOARD_NAVIGATION_EVENT.ENTRY_REJECTED]:
      KEYBOARD_NAVIGATION_NODE.NORMAL,
    [KEYBOARD_NAVIGATION_EVENT.EDITING_STARTED]:
      KEYBOARD_NAVIGATION_NODE.EDITING,
    [KEYBOARD_NAVIGATION_EVENT.HINT_STARTED]:
      KEYBOARD_NAVIGATION_NODE.HINT,
    [KEYBOARD_NAVIGATION_EVENT.SCROLL_SELECTION_STARTED]:
      KEYBOARD_NAVIGATION_NODE.SCROLL_SELECTING,
    [KEYBOARD_NAVIGATION_EVENT.SCROLL_STARTED]:
      KEYBOARD_NAVIGATION_NODE.SCROLL_ACTIVE,
    [KEYBOARD_NAVIGATION_EVENT.SHORTCUT_HELP_STARTED]:
      KEYBOARD_NAVIGATION_NODE.SHORTCUT_HELP,
  }),
  [KEYBOARD_NAVIGATION_NODE.EDITING]: Object.freeze({
    [KEYBOARD_NAVIGATION_EVENT.EDITING_CONTINUED]:
      KEYBOARD_NAVIGATION_NODE.EDITING,
    [KEYBOARD_NAVIGATION_EVENT.EDITING_ENDED]:
      KEYBOARD_NAVIGATION_NODE.NORMAL,
  }),
  [KEYBOARD_NAVIGATION_NODE.HINT]: Object.freeze({
    [KEYBOARD_NAVIGATION_EVENT.HINT_INPUT_CHANGED]:
      KEYBOARD_NAVIGATION_NODE.HINT,
    [KEYBOARD_NAVIGATION_EVENT.HINT_CANCELLED]:
      KEYBOARD_NAVIGATION_NODE.NORMAL,
    [KEYBOARD_NAVIGATION_EVENT.HINT_CLOSED_FOR_ACTIVATION]:
      KEYBOARD_NAVIGATION_NODE.NORMAL,
  }),
  [KEYBOARD_NAVIGATION_NODE.SCROLL_SELECTING]: Object.freeze({
    [KEYBOARD_NAVIGATION_EVENT.SCROLL_SELECTION_INPUT_CHANGED]:
      KEYBOARD_NAVIGATION_NODE.SCROLL_SELECTING,
    [KEYBOARD_NAVIGATION_EVENT.SCROLL_SELECTION_CANCELLED]:
      KEYBOARD_NAVIGATION_NODE.NORMAL,
    [KEYBOARD_NAVIGATION_EVENT.SCROLL_SURFACE_SELECTED]:
      KEYBOARD_NAVIGATION_NODE.SCROLL_ACTIVE,
  }),
  [KEYBOARD_NAVIGATION_NODE.SCROLL_ACTIVE]: Object.freeze({
    [KEYBOARD_NAVIGATION_EVENT.SCROLL_COMMAND]:
      KEYBOARD_NAVIGATION_NODE.SCROLL_ACTIVE,
    [KEYBOARD_NAVIGATION_EVENT.SCROLL_CANCELLED]:
      KEYBOARD_NAVIGATION_NODE.NORMAL,
  }),
  [KEYBOARD_NAVIGATION_NODE.SHORTCUT_HELP]: Object.freeze({
    [KEYBOARD_NAVIGATION_EVENT.SHORTCUT_HELP_CLOSED]:
      KEYBOARD_NAVIGATION_NODE.NORMAL,
  }),
});

export function transitionKeyboardNavigation(node, event) {
  return KEYBOARD_NAVIGATION_GRAPH[node]?.[event] ?? null;
}
